name: Keep Streamlit App Alive

on:
  schedule:
    - cron: '0 9 * * *'
    - cron: '0 21 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git pull origin main
          git commit --allow-empty -m "Keep Streamlit app alive"
          git push origin main